# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sam Groenjes
title: Machine Learning Engineer
email: samuel.groenjes@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: 
github_username: sgroenjes
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced machine learning engineer skilled in software development, platform engineering, and natural language processing. Proficient in TensorFlow, PyTorch, Python, and
  AWS. Strong foundation in data science and experience working with machine learning libraries and frameworks. Seeking to use skills and experience to make a positive impact in a
  new role.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vesuvius Scrolls Ink Detection
        additional_links:
          - title:  sgroenjes/vesuvius-scrolls-ink-detection
            icon: fab fa-github
            url: https://github.com/sgroenjes/vesuvius-scrolls-ink-detection
        description: |
          Working files for my competition submission in Kaggle competition https://www.kaggle.com/competitions/vesuvius-challenge-ink-detection
      - layout: left
        title: BERT Emotions
        additional_links:
          - title:  sgroenjes/BERT-emotions
            icon: fab fa-github
            url: https://github.com/sgroenjes/BERT-emotions
        description: | 
          A fine-tuned BERT model to detect emotions from text.
      - layout: left
        title: TinyML Keyword Search
        additional_links:
          - title:  sgroenjes/Key-Word-Search-TinyML
            icon: fab fa-github
            url: https://github.com/sgroenjes/Key-Word-Search-TinyML
        description: |
          Arduino project using TinyML to detect keywords from audio
      - layout: left
        title: Foxxy Pis
        additional_links:
          - title:  sgroenjes/foxxy-pis
            icon: fab fa-github
            url: https://github.com/sgroenjes/foxxy-pis
        description: |
          A Nodejs + Vue app to help hunt foxes in Wireless Capture the Flag. Meant to run on a pi with bluetooth dongle and SDR. Accessed from a phone on the pi's network (foxes are clever, gotta be sneaky).
      - layout: left
        sub_title: <i>More to come...</i>
        additional_links:
          - title: HuggingFace
            icon: fa-solid fa-face-smile-beam
            url: https://huggingface.co/xaeroq
        description: |
          Also checkout my HuggingFace models for various Atari Games: <a href="https://huggingface.co/xaeroq" target="_blank"><img src="https://huggingface.co/front/assets/huggingface_logo-noborder.svg" width="20" height="20"/></a>

          
      - layout: center
        description: |
          ![alt text](/images/sideprojects.jpg "Side Projects")
        
  - title: Experience
    layout: list
    content:
      - layout: top-right
        title: Dark Wolf Solutions
        sub_title: Principal (Machine Learning Engineer / DevOps Engineer)
        caption: January 2023 - Present
        link: https://darkwolfsolutions.com/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          • DarkWolfGPT: Technical lead on the development of an internal tool that utilizes fine-tuned open source LLMs (GPT-J) and integrates company documents and code
        
          • Technical proposal writer:
        
            • Digital Beaker: Investigate using machine learning techniques to mitigate Bluetooth security risks
            
            • Object tracking: Multiple object tracking for static and dynamic environments using YOLOv8 and ByteTrack
            
            • Talent Management: AI toolkit for analyzing resume and job description pairs

      - layout: top-right
        title: Dark Wolf Solutions
        sub_title: Senior Associate (Machine Learning Engineer / DevOps Engineer)
        caption: January 2021 - December 2022
        link: https://darkwolfsolutions.com/
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs

          • Responsible for designing a skill identification model that extracts standardized skills from free text resumes and job descriptions using technologies like Named Entity Recognition and Transformers
          
          • Ran experiments in Google Cloud Platform using Document AI and AutoML for a feasibility study
          
          • Responsible for developing, integrating, deploying, maintaining and operating all aspects of the organization’s IL5 Production platform
          
          • DevSecOps of containerized mission application workloads in production environment
          
      - layout: top-right
        title: Dark Wolf Solutions
        sub_title: Associate (Software Engineer)
        caption: August 2018 - December 2020
        link: https://darkwolfsolutions.com/
        description: |
          • Designed and developed web interface that utilized open source routing software (Java)
          
          • Wrote custom backend API to manage application servers on Pivotal Cloud Foundry (NodeJS)
          
          • Deployed and maintained CI/CD pipelines across multiple environments with Jenkins/GitLab

  - title: Certifications & Training
    layout: text
    content: |
      Google Professional Machine Learning Engineer Certification, 2022

      CompTIA Security+ Certification, 2021

      Google Professional Cloud Security Engineer Certification, 2021

      Google Professional Cloud Developer Certification, 2020

      HuggingFace Deep Reinforcement Learning Class

      HarvardX TinyML Professional (Audit)

      DeepLearning.AI Machine Learning for Production (MLOps) Specialization

      Coursera Preparing for Google Machine Learning Engineer

      NVIDIA DLI Building Transformer-Based NLP Applications

      DeepLearning.AI Generative Adversarial Networks Specialization

      Coursera Machine Learning for Trading

      DeepLearning.AI Tensorflow Developer Professional

      DeepLearning.AI Natural Language Processing Specialization

      DeepLearning.AI Deep Learning Specialization

      DeepLearning.AI Machine Learning Specialization
        
  - title: Education
    layout: list
    content:
      - layout: top
        sub_title: Master of Science in Artificial Intelligence & Machine Learning
        # sub_title: BS Computer Science
        caption: Colorado State University Global, Jan 2023 - Present
        # quote: >
        #   Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   <b></b>
      - layout: top
        sub_title: Bachelor of Science in Computer Science
        # sub_title: BS Computer Science
        caption: University of Nebraska - Omaha, Graduated May 2018
        # quote: >
        #   Short institution or course description (optional)
        # description: | # this will include new lines to allow paragraphs
        #   <b>University of Nebraska - Omaha</b>
      
  - title: Key Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      • Machine learning • Software development • Python • NodeJS
      • Google Cloud • AWS • TensorFlow • Pytorch • Natural Language Processing • Large Language Models • Computer Vision • Deep Learning
      • Regression • Boosted Trees • Clustering • Reinforcement Learning
      • Git • CI/CD • NumPy • Pandas • Plotly • SQL

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
